### ISSUE TITLE
Duplicate saves posted to ledger

### ISSUE THREAD

**Issue by alerque** [bradyt/cone#14]
I haven't figured out exactly the right set of circumstances to duplicate this, but I've ended up with a bunch of duplicate entries saved in my ledger file from Cone since the last F-Droid release.

I think there is some race condition where the screen does not move on or the save button doesn't disable itself right away. Maybe it's waiting on confirmation or something before drawing the next screen, but meanwhile it accepts another save command.

**Comment by bradyt** [comment]
Sorry about that. I wonder if what's going on is simply that after saving, cone is not automatically clearing the entry. You can in fact hit the save button again. The data is not cleared, the page is not closed, until you hit the back button. I'm hoping that is the issue. I agree I should update that, for example, like the behavior in MoLe, where saving closes out the page.

**Comment by alerque** [comment]
It sounds like you're trying to make it too complicated. Trying to be too fancy and second guessing the user makes for bad UX.

* Transactions that have not successfully saved should stay in memory (and hence the UI) until they are explicitly discarded or successfully saved.

* Ones that have saved should go away. Some sort of confirmation should be presented and the data entry UI should be cleared.

* The interface should be clear about what state it is in. When you hit save, the data entry UI should be locked/greyed/hidden or something, and the status of the save reported on.

The current UI (and workflow UX) is unexpected and causes data errors and user confusion.

**Comment by daraul** [comment]
I just used the app and a toast message appeared at the bottom of the screen when my posting was made, though the inputs didn't clear themselves.

**Comment by bradyt** [comment]
There is a fix in v0.1.2, at https://github.com/bradyt/cone/commit/24d347ca7dd20b9f819747f1e255dd5cafdad16f.

The new behavior will be that successful save will exit the entry form and show snackbar in previous screen.

You can test this with the instructions for running the app, in the README, or it is available on Google Play right now, or you can wait for the merge request to F-Droid described at https://github.com/bradyt/cone/issues/18.

I would close this, as this eliminates the issue as originally described.

@alerque , your ideas for the transaction draft to be saved in memory, and UI/UX, are great, I would like to implement that at some point. It may take some refactoring, or be better to wait for such. I am not sure when I will get to this, but it is on my list. If anyone feels it is more urgent, feel free to open distinct issue. Or feel free to comment here, or on IRC, Matrix, email, etc, with ideas, if you prefer.

**Comment by bradyt** [comment]
> - The interface should be clear about what state it is in. When you hit save, the data entry UI should be locked/greyed/hidden or something, and the status of the save reported on.

I think the internals of the app are not even clear on what state it is in. The finishing of the save is coded asynchronously. I need to protect the UI against that. The add button should be disabled immediately, until the save returns. I think this oversight allows very rapid presses of the save button to add duplicates still, and can crash the app.

Apologies for this bad fix.

**Comment by bradyt** [comment]
I attempted to disable the save button before write, in v0.2.2, at https://github.com/bradyt/cone/commit/fafa66f4001db42f2c1f421744ea79ac48abdcb5, but it is still possibly to crash the app and insert a duplicate entry, if the save button is pressed rapidly.

**Comment by bradyt** [comment]
There's now a boolean `saveInProgress` which should prevent duplicate saves,
from [v0.2.9/src/state_management/file_model.dart#L57-L73](https://github.com/bradyt/cone/blob/v0.2.9/cone_android/lib/src/state_management/file_model.dart#L57-L73).

```dart
  Future<void> appendTransaction({
    String transaction,
    void Function() notifyListeners,
  }) async {
    if (!saveInProgress) {
      _saveInProgress = true;
      notifyListeners();
      try {
        await appendFile(uri, transaction);
      } on PlatformException catch (_) {
        rethrow;
      } finally {
        _saveInProgress = false;
        notifyListeners();
      }
    }
  }
```
