### ISSUE TITLE
Autocompletion suggesting comments

### ISSUE THREAD

**Issue by bkqtnte10** [bradyt/cone#15]
When I'm using this notation with comments in my ledger file:
```
2014/1/29  Phone bill  ; landline bill
    ; landline bill
    Assets:Checking                           $50.00
    Expenses:Phone                           $-50.00
```

The autocompletion will suggest "; landline bill" as account. I think it should only suggest accounts.

Screenshot for clarification.
![Screenshot_20190721-115649_cone](https://user-images.githubusercontent.com/42800803/61589743-0a2f2880-abaf-11e9-95ab-96d40c3c06b3.png)

**Comment by bradyt** [comment]
Thank you for the issue @bkqtnte10 , this is fixed in v0.2.1, at https://github.com/bradyt/cone/commit/a4bcb887481761a9909dac8b3f0cf6b8c8e52daa.
