### ISSUE TITLE
Wrap multi-word commodities in double quotes

### ISSUE THREAD

**Issue by daraul** [bradyt/cone#16]
Sometimes a posting can take this form:

```
2019/07/23 * Bus
    assets:wallet                 -120.00 GYD
    expenses:transportation:bus    1 "Cummings Lodge to Middle Street"
```

Note the "Cummings Lodge..." commodity wrapped in uplifted commas. I can already input a custom commodity in cone, but it isn't wrapped in uplifted commas, so it breaks the ledger file. 

See https://www.ledger-cli.org/3.0/doc/ledger3.html#Naming-Commodities for some information

**Comment by bradyt** [comment]
Thank you for the issue.

I'll link to https://plaintextaccounting.org/quickref/, for convenience in the discussion. Though, the reference may not be up to date everywhere.

- Quick fix: I think user can add quotes manually, in entry field
- Longer fix: We should be able to detect whitespace (and digits) in the commodity field, and conditionally wrap with double quotes.
  - It appears to be the same expectation in ledger and hledger users. And beancount reportedly does not even allow spaces in commodities, so I don't think we're making it harder to possibly cover beancount data entry as the app evolves.
  - Besides other issues being more pressing, I'd like to make sure to add unit tests, and possibly widget tests, even though this _seems_ to be a trivial change. The conditional alone should at least avoid errors effecting anyone that only uses usual commodities.

**Comment by bradyt** [comment]
This will be fixed in next release, via https://github.com/bradyt/cone/commit/dba73a8365805982696de5faa1c156164f61c556.
