### ISSUE TITLE
Some entries not getting saved

### ISSUE THREAD

**Issue by e18r** [bradyt/cone#19]
I experienced an issue today whereby entries didn't get saved after pressing the save button *and* receiving the confirmation text. I wasn't using the latest version (I just updated it). I'm gonna try to make this reproducible. I'm creating this here in case anybody has more information or clues on how to make it reproducible.

Current (very weak) hipotheses:
* It happens when the file is large (55KB)
* It happens when you swhich from one file to another

I haven't really tested these hipotheses yet. Feel free to add more. Any help welcome.

**Comment by bradyt** [comment]
Oh, very sorry about that. Which version of the app was it?

**Comment by bradyt** [comment]
Are you able to build flutter apps, so that you can possibly verify a reproduce on the original version?

Or I think F-Droid shares the most recent three versions, maybe you had one of those? I think that switching files was only an option on version 0.2.0, and so F-Droid will show 0.2.0, 0.2.1, 0.2.2 currently.

**Comment by e18r** [comment]
I updated the app without checking that first, but looking at the release dates, it was probably 0.2.0. I'll try to reproduce on the latest version, and if I'm successful, I'll try building from source.

**Comment by e18r** [comment]
I haven't been able to reproduce in the current version. I suspect it got solved already. I'm gonna close this issue for now and reopen it in case it happens again. Thank you!

**Comment by bradyt** [comment]
I tried with a large file (1000 lines), I actually only saw crashing on the autocomplete. Then I tried with half the size (still 90 KB), and I couldn't reproduce the issue, on 0.2.0. For example, I wasn't sure if I could press save and then back quickly.

Consider, another user on IRC's #plaintextaccounting just reported a similar issue as yours, so I'm just not sure how to reproduce it. They did mention they were using a third party app to sync their local directory to Dropbox. But that doesn't seem like a cause.

I guess we hope this doesn't reoccur. Thank you still for reporting it, it's important to have the issue tracking started.

**Comment by e18r** [comment]
No, thank *you*, @bradyt, for the continuous development of this app and for always caring about issues, even those which aren't reproducible. I suspect that version 0.2.2 solves the issue, because I think it was related to hitting the save button, then changing the text, and then hitting the save button again, which is not possible anymore since now when you hit the save button the new entry screen goes away. Dropbox is known for causing lots of strange issues to files, but in my case I use git.

I hope to be able to contribute in the future! Take care.
