### ISSUE TITLE
App is empty

### ISSUE THREAD

**Issue by MartyLake** [bradyt/cone#2]
Hello,
App currently shows "flutter demo app".

**Comment by bradyt** [comment]
@MartyLake, `0.1.0` is on f-droid now, thank you for your patience.

**Comment by Aerex** [comment]
The app still appears to be empty 

![screenshot_20190226-072315](https://user-images.githubusercontent.com/5360960/53415694-778bb400-3997-11e9-9afa-e71ac426aadd.png)

**Comment by bradyt** [comment]
@Aerex, thank you for the report. Can you try refreshing the f-droid repo and expanding that versions section in your screenshot? Yours might be showing `v0.0.0` instead of `v0.1.0`.
