### ISSUE TITLE
Transactions not getting added

### ISSUE THREAD

**Issue by bradyt** [bradyt/cone#23]
An IRC user was reporting that about once a day, adding a transaction would not take.

I've been able to reproduce this after a day of using the app. They stated they were using Documents folder. I reproduced the issue with Google Drive, so it doesn't seem particular to any user choice.

I will continue using the app, looking for clues as to what causes it. I almost thought it was because I hadn't "refreshed" the file contents, but that doesn't seem consistent with how the code works. I had also refreshed the file in the Drive interface. That doesn't seem likely to be the issue, since other user was seeing the issue even with a non-synced phone in local Documents. Thought at one point they mentioned they were pointing a third part app to sync Dropbox upon those files.

**Comment by bradyt** [comment]
Might be related, https://github.com/bradyt/cone/issues/19.

**Comment by delexi** [comment]
I hit the problem of transactions not getting saved with version 0.2.3. I use a file that is located in a folder which is synced by syncthing. In contrast to the problem described above, in my case the app reliably did not save any transaction. I don't know when it started. To get me out of this state, I went to the settings and "reselected" the same file. After that it was working fine again.

**Comment by delexi** [comment]
I found a way to reproduce this problem reliably. I cannot add any transactions after restarting my phone.

**Comment by delexi** [comment]
I am no Android developer, so this might make no sense. But couldn't we request the permission in question each time the user opens the ads transaction dialog? What would the user see if we did this? Would they be prompted each time?

**Comment by bradyt** [comment]
I think whether the permission can persist on reboot could be assigned at time of picking, and UI should relay that information to the user, with an alert, and some sort of entry in the file info dialog. My guess is, there's no reason to request that permission again. But starting by increasing the feedback to user (rather than silently failing) might help us determine what's going on.

As for knowing if it's writable at time of adding the transaction, the UI in general should be checking this; at what all times it should check, I'm not sure yet. The minimal solution for now, might be easier to code once I finish a refactor. Our first minimal solution could be, if the save button does not work, the app should hold the state of the transaction in memory, let the user know it did not write, and then the user can reselect a URI. When the user opens the data entry form again, the transaction state will be pulled from memory.

**Comment by bradyt** [comment]
I've uncovered a plausible candidate for the issue. The arguments to `takePersistablePermissions` were only passed a _read_ permission, not also a _write_ permission. So perhaps after rebooting your Android device, you may suddenly not have write permissions. I think this is consistent with some of what I saw, where I could see new transactions added from other devices, but not the new transactions added from cone. At least, I was able to reproduce the issue, by simply selecting a file, then rebooting device.

The fix for that will be in v0.2.6+14. I expect it will be on Google Play in a few hours, and on F-Droid in less than a week. First the F-Droid bot makes a commit, which you can watch for here: https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/info.tangential.cone.yml. Then I think they rebuild in less than two days after that, to arrive on store.

I hope this solves at least most of the problem. I'm still working on the refactor, so subtle issues may be solved along the way. For example, better user feedback in unlikely event the URI disappears.

**Comment by delexi** [comment]
I just installed 0.2.6 Form f-droid, restarted my phone, added a transaction, which did not appear  in the file. After reselecting the file, everything worked fine. Same behavior as previously with 0.2.3.

**Comment by bradyt** [comment]
Thank you for report. Sorry about the app.

From your description, it is not clear to me if you had a URI selected before the app update, and so maybe we still expect a reboot to break write permissions. With a freshly selected URI, does reboot still cause breakage?

Also, what document provider are you selecting from? Nextcloud seems to have known breakage in another issue here, https://github.com/bradyt/cone/issues/31.

**Comment by bradyt** [comment]
Oh, glad your latest issue was temporary. Thank you for reporting, someone may run into same misunderstanding.

**Comment by bradyt** [comment]
The issue as originally filed, seems to be fixed.

Though, improvement is still needed in the flow of append step, for example, decoupling the append process from the UI state. Also, catching errors and notifying user appropriately. Those can be new issues. I may add such issues soon if noone else does.

**Comment by e18r** [comment]
Today, end of the month, I was reconciling my accounts, and realized many transactions were missing. I suspect it's related to this bug. I just updated to version 0.2.12. I'll let you know if it happens again. Thank you!

**Comment by bradyt** [comment]
Sorry about that! Yes I hope it was just I had forgotten to persist write permissions across device reboot, addressed in this diff:

```diff
-          .takePersistableUriPermission(uri, Intent.FLAG_GRANT_READ_URI_PERMISSION);
+          .takePersistableUriPermission(uri,
+              Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
```

Referencing the [changelog](https://github.com/bradyt/cone/blob/master/cone_android/CHANGELOG.md), that was fixed in v0.2.6, so if you have v0.2.12, excellent.

Please note, v0.2.13 has option to reverse sort, so it will be easier to keep an eye on the most recently added transaction.

**Comment by e18r** [comment]
Awesome! Can't wait to have it on F-Droid!

**Comment by e18r** [comment]
After two more months of using Cone on a daily basis, I haven't found any issues with missing transactions anymore. Thank you! It might make sense to remove the warning from F-Droid.

P.S. I couldn't find any donation addresses.

**Comment by bradyt** [comment]
Here are some donation addresses for convenience.

- paypal: https://www.paypal.me/bradytrainor
- bitcoin: 3AVZKz1EFhKzU2wuqZmJzjercKBakRmpAR
- ethereum: 0x1c99F2E13B9BC204a70dbc8Add54b37Efdf24516

Not sure when I'll get around to modifying f-droid. Feel free to ask them to change, if you think this project is stable enough to remove red tape.

Similar comment at https://github.com/bradyt/cone/issues/24#issuecomment-562994348.
