### ISSUE TITLE
Put up red tape

### ISSUE THREAD

**Issue by bradyt** [bradyt/cone#24]
With the previous issues of duplicate saves, and now issues with transactions not getting saved, it is time to prioritize putting up some sort of red tape. Probably starting with Google Play.

- https://github.com/bradyt/cone/issues/14
- https://github.com/bradyt/cone/issues/23

Maybe I should start with making the Google Play release only available as alpha, etc. Then add notes to description at F-Droid, then even something at README here. These issues seem severe enough.

**Comment by ds6** [comment]
The tape is still up on F-Droid.

**Comment by bradyt** [comment]
Feel free to ask f-droid for modifications, if you find this project is stable enough.

Maybe it should just be changed to a more generic red tape, like "This project is still in beta", or whatever it's called when we're still in version zero.

**Comment by bradyt** [comment]
Remove of red tape is merged at fdroid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6952.

**Comment by ds6** [comment]
Nice. I brought it up since you had fixed those issues that were causing such major issues. I never did put a commit in to F-Droid...
