### ISSUE TITLE
Support for payee directive

### ISSUE THREAD

**Issue by delexi** [bradyt/cone#27]
This is a feature request for the payee directive. The app already handles account directives such as `account Expenses:Food` and uses them for auto completion. The same could be done for payees with lines such as `payee Bakery`.

I use a simple text file for entering transactions on the go with cone. After each import into ledger I clear said file and fill it with `ledger accounts | sed 's/^/account /'` command. This way cone does not need to handle big files and I still get an up to date list of accounts for auto completion. I would like to have the same for payees as well.

**Comment by bradyt** [comment]
This is a great idea.

I was hoping to move towards a single ledger format, especially, hledger. Adding `payee` to file would break hledger. But parsing it won't hurt those who avoid it. Later, we could allow users to designate a second file for read only, to generate autocompletion. If an hledger user puts their `payee` directives there, they could continue using their journal for the financial notes, and reap the benefits of `payee` towards autocompletion. In summary, it shouldn't hurt if we start parsing the payee directives now.

I don't know when I can get to this. There are a couple of severe bugs, as well, I'm trying again at writing a full parser.

If someone can get to this, please do so. I think you'll need to add a regex to the description autocompletion, similar to that found in the account autocompletion. Here's some quick copy/pastes from existing source code, with brief notes.

```dart
    // add something like this
    } else if (line.startsWith('account')) {
      result = line.replaceFirst('account', '').trim();

// probably somewhere in here
String getTransactionDescriptionFromLine(String line) {

      // and add unit tests at least as effective as this
      expect(getAccountNameFromLine('account a:b:c'), 'a:b:c');
```

**Comment by alerque** [comment]
See [hledger issue 864](https://github.com/simonmichael/hledger/issues/864).

**Comment by bradyt** [comment]
Presumably fixed in next release, via https://github.com/bradyt/cone/commit/42e796f522810789944f6a4053279f1cf39733a2.
