### ISSUE TITLE
Provide more feedback when file selection must be mime type text/plain

### ISSUE THREAD

**Issue by bradyt** [bradyt/cone#28]
> I was quite confused today when I wanted to initialize cone because it wouldn't let me choose `.dat` files. It took me a while to figure out it only supports `.txt` files. 

> Maybe until this feature is done we can at least give the users a little hint?

_Originally posted by @Anachron in https://github.com/bradyt/cone/issues/17#issuecomment-523153539_

**Comment by bradyt** [comment]
@Anachron, if you clear the app memory, you should see that with no file linked, the home page says "Please select a .txt file", from https://github.com/bradyt/cone/blob/v0.2.3/lib/src/home.dart#L107-L108:

```dart
        if (fileContents == null) {
          return 'Please select a .txt file';
```

I think improving this aspect of the UI is not a priority at this time, given more pressing issues and features. Though if you have ideas on a solution that is very elegant and effective, I would like to hear them. Ideally, it should take into account the [framework](https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT) we use to access a file, and possibly even any future strategies for file access. The simpler, the better. For example, wordy instructions require more effort at [localization](https://en.wikipedia.org/wiki/Internationalization_and_localization).

Even if I add a similar note to the file picker button, if there's a previously selected file, users will not see the message. So this suggests perhaps needing an additional dialog. Which adds more complexity too early, in my opinion. I think it can wait, both for other more pressing issues/features, and in case I am doing more work on file selection in general at some point.

**Comment by bradyt** [comment]
I'm closing the issue. I think we won't see this problem arise the exact same way after `v0.2.4+12`, where the mimetype `application/octet-stream` is added to document picker.

If this is not clear or you disagree, please let me know.

**Comment by Anachron** [comment]
No I totally agree, thank you for your effort and have a good day!
