### ISSUE TITLE
Settings button doesn't do anything

### ISSUE THREAD

**Issue by ahartschen** [bradyt/cone#4]
I recently installed Cone from f-droid. When I click on the settings button nothing happens.

I'm using a Galaxy S8 running Android Oreo 8.0. Please let me know if you need any more details.

**Comment by bradyt** [comment]
@ahartschen, yes you're right, I had plans for things to add. I've cleaned up the app a little bit in `v0.1.1`, removing unused and unimplemented items. The [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/4533) to f-droid has been slower this time.

Here's the diff for the Home widget that will remove the unimplemented config button. https://github.com/bradyt/cone/commit/206eafc9d552be7950a52d1f481984c7e0a96051#diff-fdb0f1b19acd549b72981218355f25db.

``` diff
modified   lib/src/flutter/home.dart
@@ -1,6 +1,5 @@
 import 'package:flutter/material.dart';
 import 'package:flutter/gestures.dart';
-import 'package:share/share.dart';
 import 'package:url_launcher/url_launcher.dart';
 
 class Home extends StatelessWidget {
@@ -8,18 +7,6 @@ class Home extends StatelessWidget {
     return Scaffold(
       appBar: AppBar(
         title: Text('cone'),
-        actions: <Widget>[
-          IconButton(
-            icon: Icon(Icons.share),
-            onPressed: () {
-              Share.share('check out my website https://example.com');
-            },
-          ),
-          IconButton(
-            icon: Icon(Icons.settings),
-            onPressed: () {},
-          ),
-        ],
       ),
       body: DefaultTextStyle(
         style: Theme.of(context).textTheme.body1,
```

**Comment by bradyt** [comment]
Release v0.1.2 is on f-droid now.
