### ISSUE TITLE
Why was the decision made to wrap non-alphabetic commodities in quotes?

### ISSUE THREAD

**Issue by charvp** [bradyt/cone#41]
I use € as my commodity sign and I don't see why it should be wrapped in quotes? [This commit](https://github.com/bradyt/cone/commit/dba73a8365805982696de5faa1c156164f61c556) added it, but gives no explanation on why. Can this maybe be made a user option?

**Comment by alerque** [comment]
I agree this is not desired behavior.

**Comment by bradyt** [comment]
Oh, I think I made a mistake.

This change originated from https://github.com/bradyt/cone/issues/16, which leads to the following excerpt from ledger-cli manual.

> if you include white-space or numeric characters, the commodity name must be enclosed in double quotes

So instead of

```dart
if (posting.currency.contains(RegExp(r'[^A-Za-z]')))
```

It should probably be,

```dart
if (posting.currency.contains(RegExp(r'[^ \t0-9]')))
```

**Comment by alerque** [comment]
That's more like it.

By the way I think `hledger` handles this differently and additionally excludes commas and periods from commodity names. This might be a bug or it might be intentional, so it's worth looking into _why_ that's the case. If it's intentional it might be worth adding those to the symbols triggering quotation.

**Comment by bradyt** [comment]
Thank you @charvp, for bringing this error to my attention.

I've expedited the initial issue, to not wrap currency symbols. The commit is at https://github.com/bradyt/cone/commit/cc7670e2ee31676e971d58d1c0e2a998299e71fc. It may already be on Google Play, and should be on F-Droid in about half a week.

Thank you @alerque, I found this at https://hledger.org/journal.html#amounts.

> If the commodity name contains spaces, numbers, or punctuation, it must be enclosed in double quotes

Another related possible issue, if the user enters `"no. 42 green apples"`, I'd assume that cone writes that as, `""no. 42 green apples""`.

**Comment by charvp** [comment]
Thanks for the quick fix! I'm loving the recent updates by the way, keep up the good work.

**Comment by bradyt** [comment]
You're welcome, and thank you!

**Comment by bradyt** [comment]
I think a reasonable solution is now at https://github.com/bradyt/cone/commit/717b814bef12d8b0f695deaa498598be91f4925b.
