### ISSUE TITLE
Input of some amounts impossible in 'de' locale

### ISSUE THREAD

**Issue by jakalx** [bradyt/cone#45]
In de locales, a ',' is used to seperate cents, however the number parsing seems to fail on such input, e.g. 17,50 gets 17.

**Comment by bradyt** [comment]
I don't see this behavior. Can you clarify which version of cone you are using?

**Comment by bradyt** [comment]
Additional information that might help:

Please clarify if by locale, you mean your phone's system locale, or the newer in-app "Number locale", which was available in v0.2.16+24, but not actually taking effect until v0.2.17+25. If you have both locales as options, please clarify what each is set as.

Please clarify which currency. I don't expect any rounding like you describe, but I could imagine a possibility of `17,00 JPY` being written as `17 JPY`, since their "minor units are unused due to negligible value."

**Comment by bradyt** [comment]
Aha, thank you for your research, I think you've brought some strange behavior to my attention.

Some nomenclature for my post: I spoke with hledger's author, and he offered a term, "inferred balancing amount". In this post, I will refer to this as the complement (calculated complement would maybe be better). So for example, the complement of 2 and 3, is -5.

The amount hint text in amount field, will either display zero or the complement, and both are formatted with zero padding, like `0,00` or `-5,00`.

Currently, the intention is that the decimal separator is derived from the number locale, and the number of decimal places is derived from the currency. Eventually, I would like to derive these from the ledger file, but that perhaps should be discussed in a separate issue.

Your issue above seems to be that the amount hint text should display the complement in more cases.

Here is what I am now noticing.

```
2019-01-01 test
  user:writes                 17,50 EUR
  amount:hint:text             0,00 EUR ; This could be improved. I think this is the issue you are raising.

2019-01-01 test
  user:writes                 17.50 EUR
  amount:hint:text          -175,00 EUR ; This doesn't make any sense, and should be fixed as soon as possible
```

I will have to do some research, into the functions I wrote for this. As soon as I have a chance. I think this raises another issue for me. I think the concept I'm looking for is code coverage, but if it's not, this is a vague mental note to perhaps write tests that are aware of the conditionals, branching, etc., in my code. Or at the very least, review all the non-trivial functions like this, that I have in a few places.

How these are written to file is reasonable.

```
2019-01-01 test
  first:account               17,50 EUR ; What cone writes a form value of "17,50" as
  second:account

2019-01-01 test
  first:account             1750,00 EUR ; What cone writes a form value of "17.50" as
  second:account
```

The `17.50 ==> 1750,00` almost suggests we need to warn the user. But perhaps fixing the displayed complement will act as a warning. The field would have previously shown `0,00` as a hint. And the fact we went with an app wide number locale decimal separator simplifies things for the user, but if we ever use the ledger file to derive instead, will make things more difficult for the user, having to remember what decimal separator they are using for each commodity.

**Comment by bradyt** [comment]
I think it's fixed at https://github.com/bradyt/cone/commit/2ba8f50961edd22e540e85ea58fb0fc2729a519c. Should be on Google Play in a few hours, and on F-Droid in a few days. Please let me know if I've missed any aspect of the issue.

For example, see passing tests at https://github.com/bradyt/cone/blob/v0.2.18/cone_lib/test/complement_test.dart#L56-L66, which has the following:

```dart
    test('Test de locale with comma', () {
      expect(
          formattedAmountHint(
              locale: 'de',
              index: 1,
              postings: expandPostings([
                ['A', '17,50', 'EUR'],
                ['B', '', 'EUR'],
              ])),
          '-17,50');
    });
```

Note that, for now, there is no calculation if the currencies are not all the same. Let me know if you have ideas on what should be displayed in that case. I might at some point move the calculated complement to a line below the postings, as sort of a total line. Then users need not rely on the calculated complement somehow displaying in a posting amount. Once there, we might have enough space to experiment with the total line showing as combination of multiple currencies. I don't know if there's a good/easy solution to displaying total as collapsed to a single currency.

Feel free to request issue reopened, or add to discussion here, or file new related issues.

Thank you again for bringing this to my attention.
