### ISSUE TITLE
Amounts do not use fixed point numbers

### ISSUE THREAD

**Issue by jakalx** [bradyt/cone#50]
Entering an amount of ```83,29 €``` ends up as ```83,29000000000001 €```.

Journal file:
```
Y 2019
D 1.000,00 €

2019-10-29 test
  a  83,29000000000001 €
  b
```

screenshots showing the steps to reproduce:

<img src="https://user-images.githubusercontent.com/1409956/67797271-c7200380-fa81-11e9-8b6d-57259a7a118f.png" width="49%"/> <img src="https://user-images.githubusercontent.com/1409956/67797272-c7200380-fa81-11e9-8ca1-ec2748284b17.png" width="49%"/>

Version: 0.2.18

**Comment by bradyt** [comment]
I think this will fix it:

```diff
modified   cone_lib/lib/src/format.dart
@@ -114,9 +114,14 @@ String padZeros({String locale, String amount, String currency}) {
 
       formatter = NumberFormat(
           '0.${'0' * decimalDigits}'
-          '${'#' * (16 - integerDigits - decimalDigits)}',
+          '${'#' * (15 - integerDigits - decimalDigits)}',
           locale);
-      return formatter.format(parsed);
+      var result = formatter.format(parsed);
+      if (parser.parse(amount) == parser.parse(result)) {
+        return result;
+      } else {
+        return amount;
+      }
     } on FormatException catch (_) {}
     return amount;
   }
modified   cone_lib/test/format_test.dart
@@ -237,5 +237,8 @@ void main() {
     test('Rubles in locale ru', () {
       testPadZeros('ru', '1,0', 'RUB', '1,00');
     });
+    test('Floating point', () {
+      testPadZeros('de', '83,29', '€', '83,29');
+    });
   });
 }
```

Hoping to push changes soon.

**Comment by bradyt** [comment]
I hope this is fixed as of https://github.com/bradyt/cone/tree/629445b7c3098fb91874b559ebab99408adaf1f9, and on Google Play as version 0.2.19. Hoping to push to F-Droid soon.
