### ISSUE TITLE
Remove duplicates from recently used transaction titles/subjects

### ISSUE THREAD

**Issue by tilman2** [bradyt/cone#51]
I'm running cone 0.2.18 (installed via F-Droid).

When entering the title/subject in the "Add transaction" activity, cone helpfully offers a list of recently used titles/subject lines to choose from. If the same title/subject has been used repeatedly in recent transactions, they show up multiple times in the drop down list as well.

To improve on the feature's usability, I suggest to remove duplicates from the recently used transaction titles/subjects to unclutter the drop down list contents.

**Comment by bradyt** [comment]
This will be fixed via

```diff
modified   cone_lib/lib/src/parse.dart
@@ -51,7 +51,7 @@ List<String> getChunks(String fileContents) =>
     getTokens(fileContents).map((Token<String> token) => token.input).toList();
 
 List<String> getPayees(String fileContents) {
-  final List<String> payees = <String>[];
+  final Set<String> payees = <String>{};
 
   for (final String chunk in getChunks(fileContents)) {
     if (chunk.startsWith('payee')) {
@@ -67,7 +67,7 @@ List<String> getPayees(String fileContents) {
     }
   }
 
-  return payees..sort();
+  return payees.toList()..sort();
 }
 
 List<String> getTransactions(String fileContents) {
```

I'll try to get this pushed soon.

**Comment by bradyt** [comment]
I hope this is fixed as of https://github.com/bradyt/cone/tree/629445b7c3098fb91874b559ebab99408adaf1f9, and on Google Play as version 0.2.19. Hoping to push to F-Droid soon.
