### ISSUE TITLE
Replace Java with Kotlin

### ISSUE THREAD

**Issue by bradyt** [bradyt/cone#52]
Maybe switching to Kotlin is debatable, but `flutter create` for new projects defaults to Kotlin.

I'm really only noticing this when I have to add `-a java` to `flutter create`, so it's sort of a minor annoyance. But potentially development on the `uri_picker` plugin will be easier. That plugin is really the only place we're writing Java at the moment.

**Comment by adimit** [comment]
FWIW, you can leave both languages in the code base, we do this at work. The interop is good enough that you can just write new files in Kotlin, then migrate old files only when you significantly refactor them. The Java code is not a liability, and a concentrated effort to rewrite everything at once is usually a fool's errand.

**Comment by bradyt** [comment]
Note, `flutter config --no-enable-android-embedding-v2` may make this easier to hack on, so that `flutter create -a kotlin --overwrite .` does not introduce an extra issue. In other words, we probably want to deal with the two issues one at a time. Whether or not we switch to kotlin, being the first issue, and the second issue being, the inevitable switch to v2 Android embedding.

Reasons to procrastinate on both, include lack of documentation and existing examples for both. Most plugins and docs use Java and the older Android embedding.

**Comment by bradyt** [comment]
After switching to file_picker_writable, and v2 embedding, we were left with only template Java, so this seemed like a good time to switch over to Kotlin. So this should be resolved by https://github.com/bradyt/cone/commit/76e15e5bc99985d570f4b414b037aff2fba8bee5 for now. Closing.
