### ISSUE TITLE
Dark theme theme vs Auto theme mode

### ISSUE THREAD

**Issue by justinjk007** [bradyt/cone#57]
Latest version of the app from the playstore.
Running Android 10 (Oneplus Oxygen OS)

When enabling auto theme mode on the app and dark theme on the whole phone the text theme seems to still use light theme colors making the text difficult to read.

However when I enable dark mode in the app the text theme is also dark theme making the app readable.

<img src="https://user-images.githubusercontent.com/12916795/72229301-895c5280-357b-11ea-91b7-6fca38bd1734.jpg" width="49%"/> <img src="https://user-images.githubusercontent.com/12916795/72229308-9c6f2280-357b-11ea-8bef-045d1d924f8a.jpg" width="49%"/>

**Comment by bradyt** [comment]
This might be fixed at https://github.com/bradyt/cone/commit/4c35a16661c276a838dfc37c55a43244093cc94a.

I don't have Android 10, so it would be great if someone could test this.

**Comment by justinjk007** [comment]
You can probably test this in an emulator.

**Comment by bradyt** [comment]
> You can probably test this in an emulator.

I can't, unfortunately. Are you able to?

**Comment by justinjk007** [comment]
Yep, can confirm same behaviour on the emulator, this is auto mode

**Comment by bradyt** [comment]
Thank you for checking.

**Comment by bradyt** [comment]
I added another attempt at a new branch, [`scratch/brightness`](https://github.com/bradyt/cone/commits/scratch/brightness). In particular, the latest commit is https://github.com/bradyt/cone/commit/1f3e74584c23a891840997e712769571580ff723.

**Comment by justinjk007** [comment]
This commit alone from master fixed the issue 3f408b2

**Comment by bradyt** [comment]
I hope this is fixed as of https://github.com/bradyt/cone/tree/629445b7c3098fb91874b559ebab99408adaf1f9, and on Google Play as version 0.2.19. Hoping to push to F-Droid soon.
