### ISSUE TITLE
Amount becomes a recurring float when adding transaction

### ISSUE THREAD

**Issue by justinjk007** [bradyt/cone#59]
I was logging my lunch today and came across this bug, this specific number seems to become a recurring decimal once I add the transaction.

I add 8.12 as the amount. Amount becomes 8.1999999 after adding.

<img src="https://user-images.githubusercontent.com/12916795/72461944-06ffa880-379e-11ea-91c0-9c759b1791f7.jpg" width="49%"/> <img src="https://user-images.githubusercontent.com/12916795/72461998-17b01e80-379e-11ea-8b2f-55e229f6c7f4.jpg" width="49%"/>

**Comment by bradyt** [comment]
This appears to be a duplicate of https://github.com/bradyt/cone/issues/50, and possibly fixed.

**Comment by justinjk007** [comment]
Hmm, at least google play version in Canada is 0.2.18 . I built it from master and tried again. Not reproducible with the master branch. Sorry for the fuzz.

**Comment by justinjk007** [comment]
Never mind, it just didn't update the app on my phone. Google play has the 0.2.19 version too.
