### ISSUE TITLE
Change default currency

### ISSUE THREAD

**Issue by PaperMountainStudio** [bradyt/cone#6]
By default, USD is prefilled to the currency fields. I don't live in a country with USD as main currency, so it is very annoying to me.
There should be a way to change that.
Thanks.

**Comment by bradyt** [comment]
Thank you for the suggestion. I had to read up on `provider` and `shared_preferences` libraries. This feature is on `master` now. Hoping to see `v0.1.3` merged to fdroid soon.

- https://gitlab.com/fdroid/fdroiddata/merge_requests/4947

**Comment by e18r** [comment]
I can confirm it's working now. Thank you so much @bradyt!

**Comment by bradyt** [comment]
Terrific, thank you! And you're welcome!

**Comment by PaperMountainStudio** [comment]
Thanks.
