### ISSUE TITLE
Location of ledger file should be configurable

### ISSUE THREAD

**Issue by bradyt** [bradyt/cone#8]
I'd like to add an option for Dropbox. Once this is done, I would like to revisit how configurable the location of the ledger is, such as choosing various local options, or Dropbox, and maybe eventually adding options for Google Drive or WebDAV. Currently, the location is hardcoded as `Documents/cone/.cone.ledger.txt`.

If I understand correctly, the two most likely possibilites for how to implement a Dropbox option, is to either

1. Use the Dropbox Chooser SDK for Android, and write a Flutter "Platform Channel", or
2. Use the Dart `http` library, and the documentation for the Dropbox API.
   
Reasons to use option 1:
1. The SDK provides a lot of conveniences
2. In particular, those conveniences seem to cover our usecase, that is, to get a file for syncing content
3. Might be less code to maintain

Reasons to use option 2:
1. I don't know how the Android ecosystem works
2. I'm not fluent in Java, especially the Java used in these ecosystems, and Java is needed to write a Platform Channel
3. Everything would be implemented inside of Flutter framework, i.e., Dart libraries, etc.
4. Will likely port more easily to iOS
5. Other Flutter apps have gone this route? But maybe because the above mentioned SDK did not cover their usecase. https://github.com/silvershadow82/dropbox-playlist
6. I feel more motivated to learn about how to use APIs in general, then learning about the Android ecosystem and the Java there
7. Hard to anticipate issues in the Android ecosystem, such as, is the Dropbox SDK compatible with AndroidX? What other types of errors will we see coming out, and how much more of the Android ecosystem would we be forced to research?
8. More likely to be compatible with f-droid?

I'm curious if there's any way to say one option is really objectively better than the other.

Here are some resources I'm aware of, if anyone is interested in helping to researching this.

- for option 1:
  - https://www.dropbox.com/developers/chooser#android
  - https://flutter.dev/docs/development/platform-integration/platform-channels

- for option 2:
  - https://www.dropbox.com/developers/documentation/http/documentation
  - https://flutter.dev/docs/cookbook/networking/fetch-data

**Comment by bradyt** [comment]
The summary is similar at https://stackoverflow.com/questions/50089612/how-to-open-a-file-downloaded-by-dropbox-in-a-flutter-app.

> If I understand it correctly, it\'s not possible to access files managed by DropBox (or any mobile app) from another app without actually integrating with DropBox directly (rather than via the file system).
> 
> DropBox has various tools that can be used for this.
> 
> The simplest one seems to be to integrate [DropBox Chooser](https://www.dropbox.com/developers/chooser) into your app, in which case a button is added to the app which allows the user to select the file from a DropBox view ([screenshot](https://www.dropbox.com/s/2suf904oiw29oa2/Android%20Chooser%20screenshot.png)).
> 
> Other options include authenticating DropBox users via OAuth then using the DropBox REST API, or including the [DropBox SDK](https://www.dropbox.com/developers/documentation), which makes doing that easier (but you have to implement it for both iOS and Android, maybe as a Flutter plugin, as there seems to be no Flutter support).
> 
> There\'s also a Dart [DropBox REST client](https://pub.dartlang.org/packages/dropbox#-readme-tab-) project on GitHub but it seems to be abandoned.
>

**Comment by alerque** [comment]
Please don't implement direct access to third party file storage systems. That is a deep rabbit hole you will never come out of (or never please everybody). Instead implement access to Android's Document Provider API. That way users can use whatever storage service they want, and all the services that provide their documents through the system interface also can be used by your app.

Note for example Android Money Manager Ex tried going down that route even using a library for many cloud storage providers, but eventually ripped it out entirely and went with the document API. The result is much better. Easier for them to support, and functions better for us end users.

**Comment by bradyt** [comment]
Thank you for the ideas, I will look into this more when I try to work on the storage again.

- https://developer.android.com/guide/topics/providers/document-provider
- https://github.com/moneymanagerex/android-money-manager-ex

**Comment by bradyt** [comment]
Mental note to myself to checkout https://pub.dev/packages/file_picker. When I looked at the source code, there was some overlap with terms described at Android's Document Provider docs.

**Comment by bradyt** [comment]
Here are some findings so far, with using the Storage Access Framework.

- These options show up in chooser when coded via `ACTION_OPEN_DOCUMENT`:
  - Local storage
  - Google Drive
  - OneDrive
  - Box 
    - Having some issues, hope to resolve soon
      - If user has not marked any files for offline usage, chooser just hangs on picking Box
      - Somehow read nor write are working
    - But Box via SAF seems to work in QuickEdit
    - This article seems to agree with the difficulty
      - https://medium.com/steadfast-innovation/open-letter-to-cloud-storage-apps-on-android-a2d0eb919fc4
    - Who knows, might be a RTFM, perhaps Box are being stricter about something
- The following cloud providers do not show up when using `ACTION_OPEN_DOCUMENT`:
  - OwnDrive
  - NextCloud
  - Dropbox

Note the link above also agrees that Dropbox does not show. See also these links:

- https://stackoverflow.com/questions/23888691/dropbox-not-seen-in-storage-access-framework-implementation
- https://www.dropboxforum.com/t5/API-Support-Feedback/Android-Storage-Access-Framework-support/td-p/147405
- https://www.dropboxforum.com/t5/Discuss-Developer-API/why-using-Intent-ACTION-OPEN-DOCUMENT-does-not-list-the-Dropbox/td-p/209654

**Comment by bradyt** [comment]
All of a sudden, Box.com is gone from SAF, and Nextcloud has appeared. The Box.com may be the result of tickets I've submitted to them. And maybe the Nextcloud appearance is from people seeing this issue? Strange timing.

**Comment by bradyt** [comment]
The feature using `ACTION_OPEN_DOCUMENT` is now available at cone version `0.2.0`. It requires Android version at least 4.4, KitKat, API 19. Users select a location such as Documents, Google Drive, etc.

I've conveniently changed the issue topic to close. The issue was originally labelled "Add option for Dropbox". Unfortunately, Dropbox has presumably not implemented a ContentProvider for `ACTION_OPEN_DOCUMENT`. This approach seems the best for now.

Issues apparently unresolved:

- The URI from box.com is not working
- Support older devices, from Android 4.1, JellyBean, API 16
- Add option to use internal storage
- Add import/export options, sharing

I hope to eventually address these. If any of these issues are a priority to you, feel free to file an issue.

**Comment by alerque** [comment]
Hooray! I just had a look and this looks quite promising. I was able to start working with a text file in Nextcloud, which means I can sync devices, which means I _might_ be able to start using Cone for data entry. I definitely be putting it though a few basic paces soon.

**Comment by bradyt** [comment]
Ugh, https://commonsware.com/blog/2019/08/06/ACTION_OPEN_DOCUMENT-may-not-be-read-write.html.

**Comment by bradyt** [comment]
> SAF has been available since Android 5.0 Lollipop, but developers tend to not use it unless required, as it has a difficult and poorly documented API, a poor user experience, poor performance, and poor reliability (largely in the form of device vendor-specific implementation issues).
